declare module "v-charts/lib/line.common"
declare module "v-charts/lib/scatter.common"
declare module "v-charts/lib/histogram.common"
declare module "v-charts/lib/pie.common"
declare module "v-charts/lib/map.common"
declare module "v-charts/lib/wordcloud.common"
